name: Test Workflow with Coverage

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'src/**/*.py'
      - 'src/backend/requirements*.txt'
      - 'src/pytest.ini'
      - '.github/workflows/test.yml'
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
    branches:
      - main
      - dev
    paths:
      - 'src/**/*.py'
      - 'src/backend/requirements*.txt'
      - 'src/pytest.ini'
      - '.github/workflows/test.yml'

permissions:
  contents: read
  actions: read
  pull-requests: write

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: 'pip'
          cache-dependency-path: src/backend/requirements*.txt

      - name: Install Backend Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/backend/requirements.txt
          pip install pytest-cov
          pip install pytest-asyncio

      - name: Check if Backend Test Files Exist
        id: check_backend_tests
        run: |
          if [ -z "$(find src/tests -type f -name 'test_*.py' 2>/dev/null)" ]; then
            echo "No backend test files found, skipping backend tests."
            echo "skip_backend_tests=true" >> $GITHUB_ENV
          else
            echo "Backend test files found, running tests."
            echo "skip_backend_tests=false" >> $GITHUB_ENV
          fi

      - name: Run Backend Tests with Coverage
        if: env.skip_backend_tests == 'false'
        run: |
          pytest --cov=. --cov-report=term-missing --cov-report=xml --junitxml=pytest.xml ./src/tests

      - name: Pytest Coverage Comment
        if: |
          always() &&
          github.event_name == 'pull_request' &&
          github.event.pull_request.head.repo.fork == false &&
          env.skip_backend_tests == 'false'
        uses: MishaKav/pytest-coverage-comment@e48ae95fa406cefacc7fbdd79949122795569961 # v1.8.0
        with:
          pytest-xml-coverage-path: coverage.xml
          junitxml-path: pytest.xml
          report-only-changed-files: true

      - name: Skip Backend Tests
        if: env.skip_backend_tests == 'true'
        run: |
          echo "Skipping backend tests because no test files were found."
